# Generated by Django 5.1.2 on 2024-11-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s02app', '0002_author_alter_coinflip_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s02app.author')),
            ],
        ),
    ]
